cart/urls.py
"""CART URL.PY"""
from django.urls import path
from . import views
app_name = "cart"
urlpatterns = [
    path("cart/", views.cart_detail, name = "cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name ="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name = "cart_remove"),
]

coupons/urls.py
from django.urls import path
from . import views
app_name = 'coupons'
urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name="order_create"),
    path('history/', views.order_history, name="order_history"),
    path('payment/', views.payment_process, name="process"),
    path('success/', views.payment_done, name="done"),
    path('canceled/', views.payment_canceled, name="canceled"),
    path("admin/order/<int:order_id>/", views.admin_order_detail,
         name="admin_order_detail"),
    path("order/<int:order_id>/", views.order_detail,
         name="order_detail"),
    path("admin/order/<int:order_id>/pdf/", views.admin_order_pdf,
         name="admin_order_pdf"),
]

shop/urls.py
from django.urls import include, path
from shop import views

app_name = "shop"
urlpatterns = [
    path("", views.product_list, name = "shop"),
    path("adminshop/add", views.ProductPostSerializer.as_view(), name = "postshop"),
    path("shop/add", views.add_product, name = "addproduct"),
    path("adminshop/category", views.CategoryAddSerializer.as_view(), name = "postcategory"),
    path("shop/<slug:category_slug>/", views.product_list, name = "product_list_by_category"),
    path("<int:id>/<slug:slug>/detail/", views.product_detail, name = "product_detail"),
    path("search/" ,views.post_search, name = "post_search"),
    path("contactus/" ,views.contact_us, name = "contact"),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
"""Forms.py"""
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    """Adding product to cart"""
    quantity =quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.Select(attrs ={"class":"form-control quantity"}))
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
"""Cart forms"""
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Category
from shop.forms import SearchForm
from cart.cart import Cart
from cart.forms import CartAddProductForm
from coupons.forms import CouponApplyForm
# Create your views here.


@require_POST
def cart_add(request, product_id):
    """Adding cart item"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        clean_data = form.cleaned_data
        cart.add(product=product, quantity=clean_data["quantity"],
                 override_quantity=clean_data["override"])
    return redirect("cart:cart_detail")


def cart_remove(request, product_id):
    """Removing item from cart"""
    try:
        cart = Cart(request)
        product = get_object_or_404(Product, id=product_id)
        cart.remove(product)
        return redirect("cart:cart_detail")
    except Product.DoesNotExist:
        return redirect("cart:cart_detail")



def cart_detail(request):
    """All items"""
    form = SearchForm()
    cart = Cart(request)
    categories = Category.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'], 'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, "cart/details.html", {'cart': cart, "categories":categories,
    "coupon_apply_form": coupon_apply_form,"form_search":form})

cart/templates/cart/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart{% endblock %}
{% block content %}

<div class="breadcrumbs">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-6 col-md-6 col-12">
<div class="breadcrumbs-content">
<h1 class="page-title">Cart</h1>
</div>
</div>
<div class="col-lg-6 col-md-6 col-12">
<ul class="breadcrumb-nav">
<li><a href="{% url 'shop:shop' %}"><i class="lni lni-home"></i> Home</a></li>
<li><a href="{% url 'shop:shop' %}">Shop</a></li>
<li>Cart</li>
</ul>
</div>
</div>
</div>
</div>

<div class="shopping-cart section">
<div class="container">
<div class="cart-list-head">
{% with total_items=cart|length %}

{% if total_items > 0 %}
<div class="cart-list-title">
<div class="row">
<div class="col-lg-1 col-md-1 col-12">
</div>
<div class="col-lg-4 col-md-3 col-12">
<p>Product Name</p>
</div>
<div class="col-lg-2 col-md-2 col-12">
<p>Quantity</p>
</div>
<div class="col-lg-2 col-md-2 col-12">
<p>Unit Price</p>
</div>
<div class="col-lg-2 col-md-2 col-12">
<p>Total Price</p>
</div>
<div class="col-lg-1 col-md-2 col-12">
<p>Remove</p>
</div>
</div>
</div>

{% for item in cart %}
{% with product=item.product %}

<div class="cart-single-list">
<div class="row align-items-center">
<div class="col-lg-1 col-md-1 col-12">
<a href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url}}
{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Product Image"></a>
</div>
<div class="col-lg-4 col-md-3 col-12">
<h5 class="product-name"><a href="{{ product.get_absolute_url }}">
{{ product.name }}</a></h5>
<p class="product-des">
<span><em>Category:</em> {{product.category}}</span>
</p>
</div>
<div class="col-lg-2 col-md-2 col-12">
<div class="count-input">
<form action="{% url 'cart:cart_add' product.id %}" method="POST">
{{ item.update_quantity_form.quantity }}
{{ item.update_quantity_form.override }}
<div class="button">
<input class ="btn" type="submit" value="Update">
</div>
{% csrf_token %}
</form>
</div>
</div>
<div class="col-lg-2 col-md-2 col-12">
<p>GH₵{{ item.price }}</p>
</div>
<div class="col-lg-2 col-md-2 col-12">
<p>GH₵{{ item.total_price }}</p>
</div>
<div class="col-lg-1 col-md-2 col-12">
<a class="remove-item" href="{% url 'cart:cart_remove' product.id %}"><i class="lni lni-close"></i></a>
</div>
</div>
</div>

{% endwith %}
{% endfor %}
{% else %}
<div class="cart-list-title">
<div class="row">
<div class="col-lg-4 col-md-3 col-12">
<h4>Your cart is empty</h4>
</div>
</div>
</div>
{% endif %}
{% endwith %}
</div>
<div class="row">
<div class="col-12">

<div class="total-amount">
<div class="row">
<div class="col-lg-8 col-md-6 col-12">
<div class="left">
<div class="coupon">
<form action="{% url 'coupons:apply' %}" method="POST">
{{ coupon_apply_form }}
<div class="button">
<button type="submit" class="btn">Apply Coupon</button>
</div>
{% csrf_token %}
</form>

</div>
</div>
</div>

<div class="col-lg-4 col-md-6 col-12">
<div class="right">
<ul>
<li>Cart Subtotal<span>GH₵{{ cart.get_total|floatformat:2 }}</span></li>
<li>Shipping<span>Free</span></li>
{% if cart.coupon %}
<li class="last">Coupon<span>{{ cart.coupon.code }}</span></li>
<li class="last">Coupon Discount<span style ="color:red">{{ cart.coupon.discount }}%</span></li>
<li class="last">Amount off<span style ="color:red">-GH₵{{ cart.get_discount|floatformat:2 }}</span></li>
<li class="last">You Pay<span>GH₵{{ cart.get_total_price_after_discount|floatformat:2 }}</span></li>
{% else %}
<li class="last">You Pay<span>GH₵{{ cart.get_total|floatformat:2 }}</span></li>
{% endif %}
</ul>
<div class="button">
<a href="{% url 'orders:order_create' %}" class="btn">Checkout</a>
<a href="{% url 'shop:shop' %}" class="btn btn-alt">Continue shopping</a>
</div>
</div>
</div>
</div>
</div>

</div>
</div>
</div>
</div>


{% endblock %}