authentications/urls.py
"""URLs"""
from django.urls import path
from . import views
app_name = "authentications"
urlpatterns = [
    path("register/", views.register, name = "register"),
    path("login/", views.user_login, name = "login"),
    path("logout/", views.user_logout, name = "logout"),
    path("forget-password/", views.user_forgot_password, name = "forget_password"),
    path("forget-password-confirm/", views.user_forgot_pass_confirm, name = "forget_password_confirm")

]

cart/urls.py
"""CART URL.PY"""
from django.urls import path
from . import views
app_name = "cart"
urlpatterns = [
    path("cart/", views.cart_detail, name = "cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name ="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name = "cart_remove"),
]

orders/urls.py
from django.urls import path
from . import views
app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name="order_create"),
    path('history/', views.order_history, name="order_history"),
    path('payment/', views.payment_process, name="process"),
    path('success/', views.payment_done, name="done"),
    path('canceled/', views.payment_canceled, name="canceled"),
    path("admin/order/<int:order_id>/", views.admin_order_detail,
         name="admin_order_detail"),
    path("order/<int:order_id>/", views.order_detail,
         name="order_detail"),
    path("admin/order/<int:order_id>/pdf/", views.admin_order_pdf,
         name="admin_order_pdf"),
]

shop/urls.py
from django.urls import include, path
from shop import views

app_name = "shop"
urlpatterns = [
    path("", views.product_list, name = "shop"),
    path("adminshop/add", views.ProductPostSerializer.as_view(), name = "postshop"),
    path("shop/add", views.add_product, name = "addproduct"),
    path("adminshop/category", views.CategoryAddSerializer.as_view(), name = "postcategory"),
    path("shop/<slug:category_slug>/", views.product_list, name = "product_list_by_category"),
    path("<int:id>/<slug:slug>/detail/", views.product_detail, name = "product_detail"),
    path("search/" ,views.post_search, name = "post_search"),
    path("contactus/" ,views.contact_us, name = "contact"),
]

authentications/models.py
"""Models for user creation"""

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


# Create your models here.
class Pharmacist(BaseUserManager):
    """Registration of the user using the BaseUserManager to create a superuser"""

    def create_user(self,email_address, password=None, first_name=None,last_name=None, phone_number=None):
        """Creation of user"""
        if not email_address:
            raise ValueError("user must have email address")

        user = self.model(
            email_address=email_address,first_name=first_name,last_name=last_name, phone_number = phone_number
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email_address, password):
        """Creation of a superuser"""
        user = self.create_user(email_address=email_address, password=password)
        user.is_active = True
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Users(AbstractBaseUser):
    """User creation model"""
    first_name = models.CharField(max_length=200, blank=False, null=True)
    last_name = models.CharField(max_length=200, blank=False, null=True)
    email_address = models.EmailField(unique=True, blank=False, null=True )
    phone_number = models.CharField(max_length=20, blank=True,  null=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email_address'

    objects = Pharmacist()

    class Meta:
        """Pre displayed field"""
        ordering = ("email_address",)

    def __str__(self):
        return f"{self.email_address}"

    def has_perm(self, perm, obj=None):
        """When user registraion has permission, then it is a superuser"""
        return self.is_superuser

    def has_module_perms(self, app_label):
        """Has permission to access the model, like create a super user"""
        return self.is_superuser

authentications/forms.py
from django import forms
from authentications.models import Users
class LoginForm(forms.Form):
    """Creating the actual form field view"""
    email_address = forms.CharField(max_length=50, required=True,
    widget=forms.EmailInput(attrs={"class":"form-control"}))
    password = forms.CharField(max_length=50,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

class UserRegistrationForm(forms.ModelForm):
    """User registration model form"""
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    email_address = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password = forms.CharField(widget= forms.PasswordInput(attrs={"class":"form-control"}),
    label="Password")
    password2 = forms.CharField(label="Confirm Password",
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

    class Meta:
        """Already contained in form"""
        model = Users
        fields = ["first_name", "last_name","email_address","phone_number"]

    def clean_password2(self):
        """Checking if passwords matches"""
        clean_data = self.cleaned_data
        if clean_data["password"]!=clean_data["password2"]:
            raise forms.ValidationError("Passwords do not match.")
        return clean_data["password2"]


class UserForgetPassword(forms.Form):
    """Forgot password form"""
    email_address = forms.CharField(max_length=50, required=True,
    widget=forms.EmailInput(attrs={"class":"form-control"}))

class UserForgetPasswordConfirm(forms.Form):
    """Forgot password form"""
    new_password = forms.CharField(max_length=50, required=True,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))
    confim_password = forms.CharField(max_length=50, required=True,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

    def clean(self):
        cd = self.cleaned_data
        new_password = cd.get("new_password")
        confim_password = cd.get("confim_password")
        if new_password != confim_password:
            raise forms.ValidationError("Password did not match")
        else:
            return cd

authentications/views.py
"""Authentication views file"""
import os
import random
import string
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.shortcuts import redirect, render
from django.contrib import messages
from django.core.mail import send_mail
from django.urls import reverse
from authentications.models import Users
from authentications.forms import LoginForm, UserRegistrationForm, UserForgetPassword,UserForgetPasswordConfirm


def generate_random_text(number):
    """Generating random characters to mumble up the reset link sent"""
    characters = string.ascii_letters + string.digits
    results = "".join(random.choice(characters) for _ in range(number))
    return results

# Create your views here.
def user_login(request):
    """Creating the user login view"""
    if request.method =="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            user = authenticate(request,email_address = clean_data['email_address'],
            password = clean_data["password"])
            if user is not None:
                login(request,user)
                messages.success(request, "Login Success")
                return redirect("shop:shop")
            else:
                messages.error(request, "Invalid Credentials, Try Again")
                return render(request,"authentications/login.html",{"form":form})
    else:
        form = LoginForm()
    return render(request,"authentications/login.html",{"form":form})

def register(request):
    """User registers view"""
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            clean_data  =form.cleaned_data
            new_user = Users.objects.create_user(
                email_address = clean_data["email_address"],
                password = clean_data["password2"],
                first_name=clean_data["first_name"],
                last_name=clean_data["last_name"],
                phone_number = clean_data["phone_number"])
            new_user.save()
            messages.success(request, "Registration Successful, Please Login")
            return redirect("authentications:login")
    else:
        form = UserRegistrationForm()
    return render(request, "authentications/register.html", {"form": form})

def user_logout(request):
    """USer logout view"""
    logout(request)
    return redirect("shop:shop")


def user_forgot_password(request):
    """Forgotten password view"""
    users = Users.objects
    forget_form = UserForgetPassword()
    if request.method=="POST":
        form = UserForgetPassword(request.POST)
        if form.is_valid():
            clean_email = form.cleaned_data["email_address"]
            try:
                user = users.get(email_address = clean_email)
                messages.success(request, "Password reset instructions sent")
                token_generator =PasswordResetTokenGenerator()
                token = token_generator.make_token(user=user)
                send_mail("Password Reset Instructions",
                f"Password resseting link:{os.getenv('PASSWORD_RESET_HOSTNAME')}authentication/forget-password-confirm/?&si={generate_random_text(50)}&iam={user}&com={generate_random_text(50)}&bus={generate_random_text(50)}&def={token}\n\n\nIf you did not trigger this action, please ignore this Email.\n\n\n Do not share this link with anyone.\n This link can only be used once",
                os.getenv("EMAIL_HOST_USER"), [clean_email])
            except Users.DoesNotExist:
                messages.error(request, "User with email does not exist")
            form.clean()
            return render(request, "authentications/forget_password.html",
            {"forget_form":forget_form})
    else:
        form = UserForgetPassword()
        return render(request, "authentications/forget_password.html",{"forget_form":form})


def user_forgot_pass_confirm(request):
    """Confirm token used to access the user object"""
    user = Users.objects.get(email_address=request.GET["iam"])
    token = request.GET["def"]
    token_generator =PasswordResetTokenGenerator()
    if token_generator.check_token(user,token):
        form = UserForgetPasswordConfirm()
        if request.method =="POST":
            form = UserForgetPasswordConfirm(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                user.set_password(clean_data["new_password"])
                user.save()
                messages.success(request,"Password reset done, please login")
                return redirect(reverse('authentications:login'))
            else:
                form = UserForgetPasswordConfirm
                messages.error(request, "Passwords do not match")
                return render(request, "authentications/forgot_password_confirm.html",
                {"pass_conf":form})

        return render(request, "authentications/forgot_password_confirm.html",{"pass_conf":form})

    else:
        messages.error(request,"Password reset link not valid")
        return redirect(reverse('authentications:login'))

authentications/templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="zxx">
<head>
<meta charset="utf-8" />
<meta http-equiv="x-ua-compatible" content="ie=edge" />
<title>{% block title %}ShopPharma{% endblock %}</title>
<meta name="description" content="" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link  type="image/x-icon" href="{% static 'images/favicon.svg' %}" rel="shortcut icon">
<link href="{% static 'css/main.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/LineIcons.3.0.css' %}" rel="stylesheet">
<link href="{% static 'css/tiny-slider.css' %}" rel="stylesheet">
<link href="{% static 'css/glightbox.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" rel="stylesheet">
</head>
<body>

<div class="preloader">
<div class="preloader-inner">
<div class="preloader-icon">
<span></span>
<span></span>
</div>
</div>
</div>

<header class="header navbar-area">

<div class="topbar">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-4 col-md-4 col-12">
<div class="top-left">
</div>
</div>
<div class="col-lg-4 col-md-4 col-12">
<div class="top-middle">
<ul class="useful-links">
<li><a href="{% url 'shop:shop' %}">Home</a></li>
<li><a href="{% url 'shop:contact' %}">Contact Us</a></li>
</ul>
</div>
</div>
<div class="col-lg-4 col-md-4 col-12">
<div class="top-end">
<div class="user">
<ul class="user-login">
    {% if request.user.is_authenticated %}
    <i class="lni lni-user"></i>
    <li>Hello {{request.user.first_name}}</li>
    <li><a href = "{% url 'authentications:logout' %}">Logout</a></li>
    {% else %}
    <li>
    <a href="{% url 'authentications:login' %}">Sign In</a>
    </li>
    <li>
    <a href="{% url 'authentications:register' %}">Register</a>
    </li>
    {% endif %}
</ul>
</div>
</div>
</div>
</div>
</div>
</div>


<div class="header-middle">
<div class="container">
<div class="row align-items-center">
<div class="col-lg-3 col-md-3 col-7">

<a class="navbar-brand" href="{% url 'shop:shop' %}">
<img src="{% static 'images/Pharma Shop.svg' %}" alt="Logo">
</a>

</div>
<div class="col-lg-5 col-md-7 d-xs-none">

<div class="main-menu-search">

<div class="navbar-search search-style-5">
<div class="search-input">
<form action="{% url 'shop:post_search' %}">
{{form_search.as_p}}
{% csrf_token %}
</div>
<div class="search-btn">
<button type="submit"><i class="lni lni-search-alt"></i></button>
</form>
</div>
</div>

</div>

</div>
<div class="col-lg-4 col-md-2 col-5">
<div class="middle-right-area">
<div class="nav-hotline">
<a href="tel:++233240021124"><i class="lni lni-phone"></i></a>
<h3>Hotline:
<span>(+233) 240 021124</span>
</h3>
</div>
<div class="navbar-cart">
{% if request.user.is_superuser %}
<div class="wishlist">
<a href="{% url 'shop:addproduct' %}">
<i class="lni lni-upload"></i>
</a>
</div>
{% endif %}
<div class="wishlist">
<a href="{% url 'orders:order_history' %}">
<i class="fas fa-history"></i>
</a>
</div>
<div class="cart-items">
<a href="{% url 'cart:cart_detail' %}" class="main-btn">
{% with total_items=cart|length %}

<i class="lni lni-cart"></i>
 <span class="total-items">{% if total_items > 0 %} {{total_items}} {% else %} 0{% endif %}
</span>
</a>

<div class="shopping-item">
<div class="dropdown-cart-header">
<span>{% if total_items > 0 %} {{total_items}} item{{ total_items|pluralize }} {% else %} Empty{% endif %} </span>
{% endwith %}
<a href="{% url 'cart:cart_detail' %}">View Cart</a>
</div>
{% for item in cart %}
{% with product=item.product %}
<ul class="shopping-list">
<li>
<a href="{% url 'cart:cart_remove' product.id %}" class="remove" title="Remove this item"><i class="lni lni-close"></i></a>
<div class="cart-img-head">
<a class="cart-img" href="{{ product.get_absolute_url }}"><img src="{% if product.image %}{{ product.image.url}}
{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="#"></a>
</div>
<div class="content">
<h4><a href="{{ product.get_absolute_url }}">
{{product.name}}</a></h4>
<p class="quantity"> {{ item.quantity }} =<span class="amount">GH₵{{ item.total_price }}</span></p>
</div>
</li>
</ul>
{% endwith %}
{% endfor %}

<div class="bottom">
<div class="total">
<span>Total</span>
<span class="total-amount">GH₵{{ cart.get_total|floatformat:2 }}</span>
</div>

<div class="button">
<a href="{% url 'orders:order_create' %}" class="btn animate">Checkout</a>
</div>
</div>
</div>

</div>
</div>
</div>
</div>
</div>
</div>
</div>


<div class="container">
<div class="row align-items-center">
<div class="col-lg-8 col-md-6 col-12">
<div class="nav-inner">

<div class="mega-category-menu">
<span class="cat-button"><i class="lni lni-menu"></i>All Categories</span>
<ul class="sub-category category-list">
{% for c in categories %}
<li>
    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
    {% endfor %}
</ul>
</div>


<nav class="navbar navbar-expand-lg">
<button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
<span class="toggler-icon"></span>
<span class="toggler-icon"></span>
<span class="toggler-icon"></span>
</button>
<div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
<ul id="nav" class="navbar-nav ms-auto">
<li class="nav-item">
<a href="{% url 'shop:shop' %}" class="active" aria-label="Toggle navigation">Home</a>
</li>
<li class="nav-item">
<a class="dd-menu collapsed" href="javascript:void(0)" data-bs-toggle="collapse" data-bs-target="#submenu-1-3" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">Shop</a>
<ul class="sub-menu collapse" id="submenu-1-3">
<li class="nav-item"><a href="{% url 'shop:shop' %}">Shop List</a></li>
<li class="nav-item"><a href="{% url 'cart:cart_detail' %}">Cart</a></li>
<li class="nav-item"><a href="{% url 'orders:order_create' %}">Checkout</a></li>
</ul>
</li>

<ul class="sub-menu collapse" id="submenu-1-4">
<li class="nav-item"><a href="blog-grid-sidebar.html">Blog Grid Sidebar</a>
</li>
<li class="nav-item"><a href="blog-single.html">Blog Single</a></li>
<li class="nav-item"><a href="blog-single-sidebar.html">Blog Single
Sibebar</a></li>
</ul>
</li>
<li class="nav-item">
<a href="{% url 'shop:contact' %}" aria-label="Toggle navigation">Contact Us</a>
</li>
</ul>
</div> 
</nav>

</div>
</div>
<div class="col-lg-4 col-md-6 col-12">

<div class="nav-social">
<h5 class="title">Follow Us:</h5>
<ul>
<li><a href="#"><i class="lni lni-linkedin"></i></a></li>
<li><a href="#"><i class="lni lni-twitter-original"></i></a></li>
<li><a href="#"><i class="lni lni-instagram"></i></a></li>
<li><a href="#"><i class="lni lni-google"></i></a></li>
</ul>
</div>

</div>
</div>
</div>

</header>

{% block content %}

{% endblock %}
<footer class="footer">

<div class="footer-top">
<div class="container">
<div class="inner-content">
<div class="row">
<div class="col-lg-3 col-md-4 col-12">
<div class="footer-logo">
<a href="{% url 'shop:shop' %}">
<img src="{% static 'images/white Pharma Shop.svg' %}" alt="#">
</a>
</div>
</div>
<div class="col-lg-9 col-md-8 col-12">
<div class="footer-newsletter">
<h4 class="title">
    Get Information  
<span>Get all the latest information, Sales and Offers.</span>
</h4>
<div class="newsletter-form-head">
<form action="#" method="get" target="_blank" class="newsletter-form">
<input name="EMAIL" placeholder="Email address here..." type="email">
<div class="button">
<button class="btn">Subscribe<span class="dir-part"></span></button>
</div>
</form>
</div>
</div>
</div>
</div>
</div>
</div>
</div>


<div class="footer-middle">
<div class="container">
 <div class="bottom-inner">
<div class="row">
<div class="col-lg-3 col-md-6 col-12">

<div class="single-footer f-contact">
<h3>Get In Touch With Us</h3>
<p class="phone">Phone:(+233) 240 021124</p>
<ul>
<li><span>Monday-Friday: </span> 9.00 am - 8.00 pm</li>
<li><span>Saturday: </span> 10.00 am - 6.00 pm</li>
</ul>
<p class="mail">
<a href="mailto:info@shoppharm.com"><span class="__cf_email__" data-cfemail="196a6c6969766b6d596a7176697e6b707d6a377a7674">info@shoppharm.com</span></a>
</p>
</div>

</div>
<div class="col-lg-3 col-md-6 col-12">

<div class="single-footer our-app">
<h3>Our Mobile App</h3>
<ul class="app-btn">
<li>
<a href="javascript:void(0)">
<i class="lni lni-apple"></i>
<span class="small-title">Download on the</span>
<span class="big-title">App Store</span>
</a>
</li>
<li>
<a href="javascript:void(0)">
<i class="lni lni-play-store"></i>
<span class="small-title">Download on the</span>
<span class="big-title">Google Play</span>
</a>
</li>
</ul>
</div>

</div>
<div class="col-lg-3 col-md-6 col-12">

<div class="single-footer f-link">
<h3>Information</h3>
<ul>
<li><a href="javascript:void(0)">About Us</a></li>
<li><a href="javascript:void(0)">Contact Us</a></li>
<li><a href="javascript:void(0)">Downloads</a></li>
<li><a href="javascript:void(0)">Sitemap</a></li>
<li><a href="javascript:void(0)">FAQs Page</a></li>
</ul>
</div>

</div>
<div class="col-lg-3 col-md-6 col-12">

<div class="single-footer f-link">
<h3>Shop Departments</h3>
<ul>
<li><a href="javascript:void(0)">Computers & Accessories</a></li>
<li><a href="javascript:void(0)">Smartphones & Tablets</a></li>
<li><a href="javascript:void(0)">TV, Video & Audio</a></li>
<li><a href="javascript:void(0)">Cameras, Photo & Video</a></li>
<li><a href="javascript:void(0)">Headphones</a></li>
</ul>
</div>
 
</div>
</div>
</div>
</div>
</div>


<div class="footer-bottom">
<div class="container">
<div class="inner-content">
<div class="row align-items-center">
<div class="col-lg-4 col-12">
<div class="payment-gateway">
<span>We Accept:</span>
<img src="{% static 'images/footer/credit-cards-footer.png' %}" alt="#">
</div>
</div>
<div class="col-lg-4 col-12">
<div class="copyright">
<p>Designed and Developed by<a href="#" rel="nofollow" target="_blank">Andrew Afful</a></p>
</div>
</div>
<div class="col-lg-4 col-12">
<ul class="socila">
<li>
<span>Follow Us On:</span>
</li>
<li><a href="#"><i class="lni lni-linkedin"></i></a></li>
<li><a href="#"><i class="lni lni-twitter-original"></i></a></li>
<li><a href="#"><i class="lni lni-instagram"></i></a></li>
<li><a href="#"><i class="lni lni-google"></i></a></li>
</ul>
</div>
</div>
</div>
</div>
</div>

</footer>


<a href="#" class="scroll-top">
<i class="lni lni-chevron-up"></i>
</a>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
<script src="{% static 'js/glightbox.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
</body>