authentications/urls.py
"""URLs"""
from django.urls import path
from . import views
app_name = "authentications"
urlpatterns = [
    path("register/", views.register, name = "register"),
    path("login/", views.user_login, name = "login"),
    path("logout/", views.user_logout, name = "logout"),
    path("forget-password/", views.user_forgot_password, name = "forget_password"),
    path("forget-password-confirm/", views.user_forgot_pass_confirm, name = "forget_password_confirm")

]

cart/urls.py
"""CART URL.PY"""
from django.urls import path
from . import views
app_name = "cart"
urlpatterns = [
    path("cart/", views.cart_detail, name = "cart_detail"),
    path("add/<int:product_id>/", views.cart_add, name ="cart_add"),
    path("remove/<int:product_id>/", views.cart_remove, name = "cart_remove"),
]

authentications/models.py
"""Models for user creation"""

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


# Create your models here.
class Pharmacist(BaseUserManager):
    """Registration of the user using the BaseUserManager to create a superuser"""

    def create_user(self,email_address, password=None, first_name=None,last_name=None, phone_number=None):
        """Creation of user"""
        if not email_address:
            raise ValueError("user must have email address")

        user = self.model(
            email_address=email_address,first_name=first_name,last_name=last_name, phone_number = phone_number
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email_address, password):
        """Creation of a superuser"""
        user = self.create_user(email_address=email_address, password=password)
        user.is_active = True
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Users(AbstractBaseUser):
    """User creation model"""
    first_name = models.CharField(max_length=200, blank=False, null=True)
    last_name = models.CharField(max_length=200, blank=False, null=True)
    email_address = models.EmailField(unique=True, blank=False, null=True )
    phone_number = models.CharField(max_length=20, blank=True,  null=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email_address'

    objects = Pharmacist()

    class Meta:
        """Pre displayed field"""
        ordering = ("email_address",)

    def __str__(self):
        return f"{self.email_address}"

    def has_perm(self, perm, obj=None):
        """When user registraion has permission, then it is a superuser"""
        return self.is_superuser

    def has_module_perms(self, app_label):
        """Has permission to access the model, like create a super user"""
        return self.is_superuser

authentications/forms.py
from django import forms
from authentications.models import Users
class LoginForm(forms.Form):
    """Creating the actual form field view"""
    email_address = forms.CharField(max_length=50, required=True,
    widget=forms.EmailInput(attrs={"class":"form-control"}))
    password = forms.CharField(max_length=50,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

class UserRegistrationForm(forms.ModelForm):
    """User registration model form"""
    first_name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    email_address = forms.CharField(widget=forms.EmailInput(attrs={"class":"form-control"}))
    phone_number = forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password = forms.CharField(widget= forms.PasswordInput(attrs={"class":"form-control"}),
    label="Password")
    password2 = forms.CharField(label="Confirm Password",
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

    class Meta:
        """Already contained in form"""
        model = Users
        fields = ["first_name", "last_name","email_address","phone_number"]

    def clean_password2(self):
        """Checking if passwords matches"""
        clean_data = self.cleaned_data
        if clean_data["password"]!=clean_data["password2"]:
            raise forms.ValidationError("Passwords do not match.")
        return clean_data["password2"]


class UserForgetPassword(forms.Form):
    """Forgot password form"""
    email_address = forms.CharField(max_length=50, required=True,
    widget=forms.EmailInput(attrs={"class":"form-control"}))

class UserForgetPasswordConfirm(forms.Form):
    """Forgot password form"""
    new_password = forms.CharField(max_length=50, required=True,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))
    confim_password = forms.CharField(max_length=50, required=True,
    widget=forms.PasswordInput(attrs={"class":"form-control"}))

    def clean(self):
        cd = self.cleaned_data
        new_password = cd.get("new_password")
        confim_password = cd.get("confim_password")
        if new_password != confim_password:
            raise forms.ValidationError("Password did not match")
        else:
            return cd

authentications/views.py
"""Authentication views file"""
import os
import random
import string
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.tokens import PasswordResetTokenGenerator
from django.shortcuts import redirect, render
from django.contrib import messages
from django.core.mail import send_mail
from django.urls import reverse
from authentications.models import Users
from authentications.forms import LoginForm, UserRegistrationForm, UserForgetPassword,UserForgetPasswordConfirm


def generate_random_text(number):
    """Generating random characters to mumble up the reset link sent"""
    characters = string.ascii_letters + string.digits
    results = "".join(random.choice(characters) for _ in range(number))
    return results

# Create your views here.
def user_login(request):
    """Creating the user login view"""
    if request.method =="POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            user = authenticate(request,email_address = clean_data['email_address'],
            password = clean_data["password"])
            if user is not None:
                login(request,user)
                messages.success(request, "Login Success")
                return redirect("shop:shop")
            else:
                messages.error(request, "Invalid Credentials, Try Again")
                return render(request,"authentications/login.html",{"form":form})
    else:
        form = LoginForm()
    return render(request,"authentications/login.html",{"form":form})

def register(request):
    """User registers view"""
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            clean_data  =form.cleaned_data
            new_user = Users.objects.create_user(
                email_address = clean_data["email_address"],
                password = clean_data["password2"],
                first_name=clean_data["first_name"],
                last_name=clean_data["last_name"],
                phone_number = clean_data["phone_number"])
            new_user.save()
            messages.success(request, "Registration Successful, Please Login")
            return redirect("authentications:login")
    else:
        form = UserRegistrationForm()
    return render(request, "authentications/register.html", {"form": form})

def user_logout(request):
    """USer logout view"""
    logout(request)
    return redirect("shop:shop")


def user_forgot_password(request):
    """Forgotten password view"""
    users = Users.objects
    forget_form = UserForgetPassword()
    if request.method=="POST":
        form = UserForgetPassword(request.POST)
        if form.is_valid():
            clean_email = form.cleaned_data["email_address"]
            try:
                user = users.get(email_address = clean_email)
                messages.success(request, "Password reset instructions sent")
                token_generator =PasswordResetTokenGenerator()
                token = token_generator.make_token(user=user)
                send_mail("Password Reset Instructions",
                f"Password resseting link:{os.getenv('PASSWORD_RESET_HOSTNAME')}authentication/forget-password-confirm/?&si={generate_random_text(50)}&iam={user}&com={generate_random_text(50)}&bus={generate_random_text(50)}&def={token}\n\n\nIf you did not trigger this action, please ignore this Email.\n\n\n Do not share this link with anyone.\n This link can only be used once",
                os.getenv("EMAIL_HOST_USER"), [clean_email])
            except Users.DoesNotExist:
                messages.error(request, "User with email does not exist")
            form.clean()
            return render(request, "authentications/forget_password.html",
            {"forget_form":forget_form})
    else:
        form = UserForgetPassword()
        return render(request, "authentications/forget_password.html",{"forget_form":form})


def user_forgot_pass_confirm(request):
    """Confirm token used to access the user object"""
    user = Users.objects.get(email_address=request.GET["iam"])
    token = request.GET["def"]
    token_generator =PasswordResetTokenGenerator()
    if token_generator.check_token(user,token):
        form = UserForgetPasswordConfirm()
        if request.method =="POST":
            form = UserForgetPasswordConfirm(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                user.set_password(clean_data["new_password"])
                user.save()
                messages.success(request,"Password reset done, please login")
                return redirect(reverse('authentications:login'))
            else:
                form = UserForgetPasswordConfirm
                messages.error(request, "Passwords do not match")
                return render(request, "authentications/forgot_password_confirm.html",
                {"pass_conf":form})

        return render(request, "authentications/forgot_password_confirm.html",{"pass_conf":form})

    else:
        messages.error(request,"Password reset link not valid")
        return redirect(reverse('authentications:login'))

authentications/templates/authentications/forget_password.html
{% extends "base.html" %}
{% block title %}Forgot Password{% endblock %}

{% block content %}
<div class="account-login section">
<div class="container">
<div class="row">
<div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
<form class="card login-form" method="POST">
<div class="card-body">
<div id="title">
    <h3>Forgot Password</h3>
    {% if messages %}
    {% for message in messages %}
    <div id = "info_container" {% if message.tags == "error" %}class= "info_container" {% else %}class= "info_containers"{% endif %} >
             <p> {{message}}</p>              
        <i class="lni lni-close"></i>
        {% endfor %}
    </div>
        {% endif %}

</div>

</div>
<div class="form-group input-group">
{{forget_form.as_p}}
{% csrf_token %}
</div>
<div class="button"> 
<button class="btn" type="submit">Send E-mail</button>
</div>
<p class="outer-link">Don't have an account? <a href="{% url 'authentications:register' %}">Register here </a>
</p>
</div>
</form>
</div>
</div>
</div>
</div>
<script>
    const info_container = document.getElementById("info_container"); 
    const x = info_container.lastElementChild;
    x.style.cursor = "pointer";
    x.addEventListener('click',()=>{
        info_container.style.display="none"
    })

</script>
{% endblock %}

authentications/templates/authentications/forgot_password_confirm.html
{% extends "base.html" %}
{% block title %}Forgot Password{% endblock %}

{% block content %}
<div class="account-login section">
<div class="container">
<div class="row">
<div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
<form class="card login-form" method="POST">
<div class="card-body">
<div id="title">
    <h3>Forgot Password</h3>
    {% if messages %}
    {% for message in messages %}
    <div id = "info_container" {% if message.tags == "error" %}class= "info_container" {% else %}class= "info_containers"{% endif %} >
             <p> {{message}}</p>              
        <i class="lni lni-close"></i>
        {% endfor %}
    </div>
        {% endif %}

</div>

</div>
<div class="form-group input-group">
{{pass_conf.as_p}}
{% csrf_token %}
</div>
<div class="button"> 
<button class="btn" type="submit">Reset Password</button>
</div>
<p class="outer-link">Don't have an account? <a href="{% url 'authentications:register' %}">Register here </a>
</p>
</div>
</form>
</div>
</div>
</div>
</div>
<script>
    const info_container = document.getElementById("info_container"); 
    const x = info_container.lastElementChild;
    x.style.cursor = "pointer";
    x.addEventListener('click',()=>{
        info_container.style.display="none"
    })

</script>
{% endblock %}

authentications/templates/authentications/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="account-login section">
<div class="container">
<div class="row">
<div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
<form class="card login-form" method="POST">
<div class="card-body">
<div id="title">
    <h3>Login</h3>
    <p>You can login using your social media account or email address.</p>
    {% if messages %}
    {% for message in messages %}
    <div id = "info_container" {% if message.tags == "error" %}class= "info_container" {% else %}class= "info_containers"{% endif %} >
             <p> {{message}}</p>              
        <i class="lni lni-close"></i>
        {% endfor %}
    </div>
        {% endif %}

</div>
<div class="social-login">
<div class="row">
<div class="col-lg-6 col-md-4 col-12"><a class="btn facebook-btn" href='{% url "social:begin" "facebook" %}'><i class="lni lni-facebook-filled"></i> Facebook
login</a></div>
<div class="col-lg-6 col-md-4 col-12"><a class="btn google-btn" href='{% url "social:begin" "google-oauth2" %}'><i class="lni lni-google"></i> Google login</a>
</div>
</div>
</div>
<div class="alt-option">
<span>Or</span>
</div>
<div class="form-group input-group">
{{form.as_p}}
{% csrf_token %}
</div>
<div class="d-flex flex-wrap justify-content-between bottom-content">
<div class="form-check">
<input type="checkbox" class="form-check-input width-auto" id="exampleCheck1">
<label class="form-check-label">Remember me</label>
</div>
<a class="lost-pass" href="{% url 'authentications:forget_password' %}">Forgot password?</a>
</div>
<div class="button"> 
<button class="btn" type="submit">Login</button>
</div>
<p class="outer-link">Don't have an account? <a href="{% url 'authentications:register' %}">Register here </a>
</p>
</div>
</form>
</div>
</div>
</div>
</div>
<script>
    const info_container = document.getElementById("info_container"); 
    const x = info_container.lastElementChild;
    x.style.cursor = "pointer";
    x.addEventListener('click',()=>{
        info_container.style.display="none"
    })

</script>
{% endblock %}

authentications/templates/authentications/register.html
{% extends "base.html" %}
{% block title %}Register{% endblock %}


{% block content %}
<div class="account-login section">
<div class="container">
<div class="row">
<div class="col-lg-6 offset-lg-3 col-md-10 offset-md-1 col-12">
<div class="register-form">
<div class="title">
<h3>No Account? Register</h3>
<p>Registration takes less than a minute but gives you full control over your orders.</p>
</div>
<form class="row" method="POST">
<div class="form-group input-group">
{{form.as_p}}
{% csrf_token %}
</div>
<div class="button">
<button class="btn" type="submit">Register</button>
</div>
<p class="outer-link">Already have an account? <a href="{% url 'authentications:login' %}">Login Now</a></p>
</form>
</div>
</div>
</div>
</div>
</div>

{% endblock %}